---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: infra
spec:
  acme:
    email: amsy810@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: testbed.104.198.118.140.nip.io
  namespace: infra
spec:
  secretName: testbed-cert
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - testbed.104.198.118.140.nip.io
  - argocd.104.198.118.140.nip.io
  - tekton.104.198.118.140.nip.io
  - harbor.104.198.118.140.nip.io
  - notary.104.198.118.140.nip.io
  - dashboard.104.198.118.140.nip.io
  - rook.104.198.118.140.nip.io
  - prometheus.104.198.118.140.nip.io
  - grafana.104.198.118.140.nip.io
  - alertmanager.104.198.118.140.nip.io
  - weave-scope.104.198.118.140.nip.io
  - yugabyte.104.198.118.140.nip.io
  - minio.104.198.118.140.nip.io
  commonName: testbed.104.198.118.140.nip.io
